[package]
name = "polybow"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {  version = "0.16.1" , features = ["wav"] }
bevy_hanabi = "0.16.0"
rand="0.9.2"
bevy_rapier2d = "0.30.0"
log = "0.4.27"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }